name: Deploy Package

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Commit changes to upm branch
        run: git subtree split --prefix=Packages/games.grumpybear.fmod.utilities --branch upm

      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "Packages/games.grumpybear.fmod.utilities/package.json"
          prop_path: "version"

      - name: Create version tag
        run:  |
          PKG_VERSION=${{steps.version.outputs.prop}}
          git ls-remote --exit-code --tags origin $PKG_VERSION && echo "Same version already exists '$PKG_VERSION'" && exit 7
          git tag $PKG_VERSION upm

      - name: Push version and upm branch
        run: git push origin upm --tags --force
